### ISSUE TITLE
The Wire.endTransmission() should not be used after the Wire.requestFrom() and other notes.

### ISSUE THREAD

**Issue by Koepel** [SMFSW/WireWrapper#2]
In the function "I2C_rd()", there is a Wire.endTransmission() after the Wire.requestFrom(). That Wire.endTransmission() can be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

Is the I2C_is_busy() for using the library in a interrupt ? I think that using the Wire library in a interrupt is already a bug on its own.

You use a repeated start between setting the register address and reading data. Every modern sensor should support that, but maybe there are somewhere I2C devices that don't like it.

A delay of 5 ms is a long time between the retries. I think that 1 ms is more than enough for every situation.

Are the retries an extra safety feature ? Do you keep track if that is really useful ? Maybe an Arduino as a Slave with a bad sketch can use it. When the I2C bus has noise or other troubles, those retries can not fix such I2C bus troubles.

When the Slave is an Arduino (with a bad sketch) a delay between writing the register address and requesting data is more helpful than retries.

**Comment by SMFSW** [comment]
> In the function "I2C_rd()", there is a Wire.endTransmission() after the Wire.requestFrom(). That Wire.endTransmission() can be removed.

I just checked wire code and that's right, send stop should already be sent.
I'll change that soon and try it on different boards & sensors before releasing the changes.

> Is the I2C_is_busy() for using the library in a interrupt ? I think that using the Wire library in a interrupt is already a bug on its own.

I first coded cI2C library which is only for AVR, and wanted WireWrapper to have same names/variables/functions to be able to switch between the 2 libs with only the include change. I did not make cI2C able to use interrupts, but this variable would be for that purpose.
Yes, WireWrapper shall not be used in interrupt as Wire already works with them!

> You use a repeated start between setting the register address and reading data. Every modern sensor should support that, but maybe there are somewhere I2C devices that don't like it.

It's a common wrapper library set to cover most sensors, but some may have different needs, that is why read and write functions are function pointers. You can have a look at [wirewrapper_advanced.ino](https://github.com/SMFSW/WireWrapper/blob/master/examples/wirewrapper_advanced/wirewrapper_advanced.ino) on how to set up custom r/w functions.

> A delay of 5 ms is a long time between the retries. I think that 1 ms is more than enough for every situation.

I'll change that to lower delay between retries.

> Are the retries an extra safety feature ? Do you keep track if that is really useful ? Maybe an Arduino as a Slave with a bad sketch can use it. When the I2C bus has noise or other troubles, those retries can not fix such I2C bus troubles.

A lot of other platforms code are using retries in case some kind of glitch happens, often with a lot of retries count, I wanted to keep the functionnality but with a customizable retries count not to spend too long trying to communicate with a faulty device.

> When the Slave is an Arduino (with a bad sketch) a delay between writing the register address and requesting data is more helpful than retries.

For this purpose, custom r/w functions can be used to add this delay.

Thanks for your notes, I'll try to make the changes soon.
Regards,
SMFSW

**Comment by Koepel** [comment]
Even if the Wire.requestFrom() would not send a stop to the I2C bus, the Wire.endTransmission() may not be used to send a stop. It is not a stop. 
There are also a few of those extra Wire.endTransmission() in the advanced example.

I noticed that we both made common reading and writing functions that return a bool. I'm glad we both came to the conclusion that all that is needed to know is whether the transaction was successful or not.

I will change the default to repeated start for [my own wrapper](https://github.com/Koepel/CommonSensorClass). Thanks.

A lot of platforms use retries, but there is also a lot of nonsense code when using the Arduino Wire library. You have only a few retries, so your code does not get stuck in something (the Wire library itself might get stuck) and at least you have something to be able to recover from a bus glitch. I'm not convinced yet and I will not add it yet to my own wrapper because of the Wire library.

**Comment by SMFSW** [comment]
Done
